version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0 
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false 
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data 
    networks:
      - elastic-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0 
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elastic-network

volumes:
  esdata: 

networks:
  elastic-network: 
    driver: bridge