version: '3.8'
services:
  kafka:
    image: apache/kafka-native
    ports:
      - "9092:9092" 
    environment:
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091

      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    container_name: elasticsearch
    environment:
      xpack.security.enabled: "false"
      discovery.type: single-node
      ES_JAVA_OPTS: -Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.0
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  meta-creator-service:
    build:
      context: .
      dockerfile: ./meta_creator.Dockerfile
    image: meta-creator-service:v1.1
    ports:
      - "3000:3000"
    environment:
      DATA_DIR: /mnt/data
    volumes:
      - ${DATA_DIR}:/mnt/data:ro
    depends_on:
      - kafka
  data-indexer-service:
    build:
      context: .
      dockerfile: ./data_indexer.Dockerfile
    image: data-indexer-service:v1.1
    ports:
      - "3001:3001"
    environment:
      DATA_DIR: /mnt/data
    volumes:
      - ${DATA_DIR}:/mnt/data:ro
    depends_on:
      - kafka
      - mongodb
      - elasticsearch
      - meta-creator-service
  stt-service:
    build:
      context: .
      dockerfile: ./stt_service.Dockerfile
    image: stt-service:v1.1
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
      - elasticsearch
      - data-indexer-service
  bds-service:
    build:
      context: .
      dockerfile: ./bds_service.Dockerfile
    image: bds-service:v1.1
    ports:
      - "3003:3003"
    depends_on:
      - elasticsearch
      - stt-service
volumes:
  esdata:

  
  
