version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  meta-creator-service:
    build: ./meta_creator
    ports:
      - "3000:3000"
    depends_on:
      - kafka

  data-indexer-service:
    build: ./data_indexer
    depends_on:
      - kafka
      - mongodb
      - elasticsearch

  stt-service:
    build: ./stt_service
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - elasticsearch

  # elasticsearch-indexer-service:
  #   build: ./elasticsearch-indexer-service
  #   depends_on:
  #     - kafka
  #     - elasticsearch

  # mongodb-storage-service:
  #   build: ./mongodb-storage-service
  #   depends_on:
  #     - kafka
  #     - mongodb

  # api-gateway-service:
  #   build: ./api-gateway-service
  #   ports:
  #     - "4000:4000"
  #   depends_on:
  #     - audio-upload-service
  #     - mongodb
  #     - elasticsearch
